import 'package:flutter/material.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_spacing.dart';

class TermsPrivacyScreen extends StatelessWidget {
  const TermsPrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 3,
      child: Scaffold(
        backgroundColor: AppColors.background,
        appBar: AppBar(
          title: const Text('Legal & Support'),
          bottom: const TabBar(
            tabs: [
              Tab(text: 'Privacy Policy'),
              Tab(text: 'Terms of Use'),
              Tab(text: 'Contact Support'),
            ],
          ),
        ),
        body: const TabBarView(
          children: [
            _PolicyView(
              title: 'Privacy Policy',
              date: 'Last Updated: July 2026',
              content: '''
SocietySphere ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by SocietySphere.

1. Information We Collect:
- Resident Profile: Name, Phone Number, Email, Flat/Tower Allocation.
- Gate Visitor Logs: Visitor Name, Contact Number, Vehicle Number, Entry/Exit Timestamps.
- Emergency SOS Data: Incident Type, Resident Metadata, Timestamps.

2. How We Use Information:
- Verifying authorized resident & visitor entry at security gates.
- Dispatching real-time visitor arrival notifications to host flats.
- Processing society maintenance payments securely via Razorpay.

3. Data Security & Isolation:
All data is stored with multi-tenant encryption (society-level RBAC isolation). We do not sell or monetize resident personal data.
''',
            ),
            _PolicyView(
              title: 'Terms & Conditions',
              date: 'Last Updated: July 2026',
              content: '''
Welcome to SocietySphere! By accessing or using our mobile application and admin services, you agree to be bound by these Terms.

1. Account Responsibility:
Residents and security personnel must maintain the confidentiality of their credentials and immediately report any unauthorized access.

2. Gate Access Protocol:
Guards must log visitor details accurately. False entry logs or bypassing security procedures may result in account suspension.

3. Payment Terms:
Maintenance bills generated by the local Management Committee are paid directly to society bank accounts via integrated payment gateways.
''',
            ),
            _PolicyView(
              title: 'Contact Support & Helpdesk',
              date: '24x7 Customer Helpdesk',
              content: '''
Need help with SocietySphere? Contact our 24x7 dedicated support team.

- Technical Support Email: support@societysphere.com
- Toll-Free Helpline: 1800-123-4567 (India)
- Operations Office: SocietySphere Tech Park, Bandra Kurla Complex, Mumbai 400051

For urgent gate emergency configuration, please contact your local Society Administrator directly through the Complaints & Helpdesk section.
''',
            ),
          ],
        ),
      ),
    );
  }
}

class _PolicyView extends StatelessWidget {
  final String title, date, content;

  const _PolicyView(
      {required this.title, required this.date, required this.content});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(AppSpacing.pagePadding),
      child: Container(
        padding: const EdgeInsets.all(AppSpacing.lg),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(AppRadius.xl),
          border: Border.all(color: AppColors.border),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title,
                style:
                    const TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 4),
            Text(date,
                style: const TextStyle(
                    fontSize: 12, color: AppColors.textSecondary)),
            const Divider(height: 24),
            Text(content,
                style: const TextStyle(
                    fontSize: 14, height: 1.6, color: AppColors.textPrimary)),
          ],
        ),
      ),
    );
  }
}
