// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEqP0hDR5zhpflZ7zTgwk5RxSulpyEwtA',
    appId: '1:43273653500:web:9c2c8c55c64a7b7f8f9b79',
    messagingSenderId: '43273653500',
    projectId: 'societysphere-b2538',
    authDomain: 'societysphere-b2538.firebaseapp.com',
    storageBucket: 'societysphere-b2538.firebasestorage.app',
    measurementId: 'G-V5C3WYBEXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnFVdWg7AwL8T_UpK1V6mznhBVHYhimWA',
    appId: '1:43273653500:android:2d22da2625510a728f9b79',
    messagingSenderId: '43273653500',
    projectId: 'societysphere-b2538',
    storageBucket: 'societysphere-b2538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm55Y6qjtBfe18V83vvOKOAmE2YU9Zwww',
    appId: '1:43273653500:ios:d5c796c4b9687df58f9b79',
    messagingSenderId: '43273653500',
    projectId: 'societysphere-b2538',
    storageBucket: 'societysphere-b2538.firebasestorage.app',
    iosBundleId: 'com.example.societysphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEqP0hDR5zhpflZ7zTgwk5RxSulpyEwtA',
    appId: '1:43273653500:web:546e2d5393ae86c58f9b79',
    messagingSenderId: '43273653500',
    projectId: 'societysphere-b2538',
    authDomain: 'societysphere-b2538.firebaseapp.com',
    storageBucket: 'societysphere-b2538.firebasestorage.app',
    measurementId: 'G-H0HW4RX4N2',
  );
}
